spring:
  application:
    name: distriapp-api
  datasource:
    username: "${USERNAME_DB}"
    password: "${PASSWORD_DB}"
    url: "jdbc:postgresql://${URI_DB}:${PORT_DB}/${NAME_DATABASE}"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: "${DEFAULT_SCHEMA}"
    open-in-view: false
  flyway:
    schemas: "${DEFAULT_SCHEMA}"
    default-schema: "${DEFAULT_SCHEMA}"